- docs/content/en/setup.md
Hello! Its look like you have a mistake in setup docs, let me fix it!
`createPinia()` doesn’t accept any arguments, but `.use()` does accept `PiniaPlugin` interface at first and least argument
> docs: fix setup block

- packages/pinia-orm/src/composables/useDataStore.ts
- packages/pinia-orm/src/connection/Connection.ts
- packages/pinia-orm/src/model/Model.ts
- packages/pinia-orm/tests/feature/repository/save.spec.ts
- packages/pinia-orm/tests/unit/model/Model_pinia_options.spec.ts
You can now add pinia optionen to the store through the model
````typescript
class User extends Model {
static entity = 'users'
@Num(0) id!: number
@Str('') name!: string
@Num(0) age!: number
static piniaOptions = {
persist: true,
}
}
````
closes #16
> feat(#16): Pass pinia options via model property

- .github/workflows/ci.yml
- docs/content/2.model/3.decorators.md
- docs/content/3.relationships/4.many-to-many.md
- docs/content/3.relationships/5.polymorphic.md
- package.json
- packages/nuxt/package.json
- packages/pinia-orm/package.json
- packages/pinia-orm/src/index.cjs.ts
- packages/pinia-orm/src/index.ts
- packages/pinia-orm/src/model/Model.ts
- packages/pinia-orm/src/model/attributes/relations/BelongsToMany.ts
- packages/pinia-orm/src/model/attributes/relations/Relation.ts
- packages/pinia-orm/src/model/decorators/attributes/relations/BelongsToMany.ts
- packages/pinia-orm/src/store/Store.ts
- packages/pinia-orm/tests/feature/relations/belongs_to_many_retrieve.spec.ts
- packages/pinia-orm/tests/feature/relations/belongs_to_many_save.spec.ts
- packages/pinia-orm/tests/feature/relations/belongs_to_many_save_custom_key.spec.ts
- pnpm-lock.yaml
adding back a relation always wanted in vuex-orm-next:
````ts
class User extends Model {
static entity = 'users'
@Num(0) id!: number
@BelongsToMany(() => Role, () => RoleUser, 'user_id', 'role_id')
permissions!: Role
}
class Role extends Model {
static entity = 'roles'
@Num(0) id!: number
}
class RoleUser extends Model {
static entity = 'roleUser'
static primaryKey = ['role_id', 'user_id']
@Attr(null) role_id!: number | null
@Attr(null) user_id!: number | null
@Attr(null) level!: number | null
}
````
> feat(pinia-orm): add belongsToMany relation function

- docs/content/2.model/4.lifecycle-hooks.md
- docs/content/2.model/5.pinia-options.md
- packages/pinia-orm/src/connection/Connection.ts
- packages/pinia-orm/src/model/Model.ts
- packages/pinia-orm/src/query/Query.ts
- packages/pinia-orm/src/repository/Repository.ts
- packages/pinia-orm/tests/feature/hooks/created.spec.ts
- packages/pinia-orm/tests/feature/hooks/creating.spec.ts
- packages/pinia-orm/tests/feature/hooks/deleted.spec.ts
- packages/pinia-orm/tests/feature/hooks/deleting.spec.ts
- packages/pinia-orm/tests/feature/hooks/saved.spec.ts
- packages/pinia-orm/tests/feature/hooks/saving.spec.ts
- packages/pinia-orm/tests/feature/hooks/updated.spec.ts
- packages/pinia-orm/tests/feature/hooks/updating.spec.ts
- packages/pinia-orm/tests/performance/save_has_many_relation.spec.ts
- packages/pinia-orm/tests/unit/repository/Repository.spec.ts
Adding local & global life cycle hooks like retrieved, creating, created, updating, updated, saving, saved, deleting, deleted.
````ts
class User extends Model {
static entity = 'users'
@Num(0) id!: number
@Str('') name!: string
@Num(0) age!: number
static updating(model: Model) {
model.name = 'John'
}
}
````
> feat(pinia-orm): add life-cycle-hooks

- docs/content/4.repository/2.retrieving-data.md
- packages/pinia-orm/src/query/Query.ts
- packages/pinia-orm/src/repository/Repository.ts
- packages/pinia-orm/tests/feature/repository/retrieves_has_or.spec.ts
- packages/pinia-orm/tests/unit/model/Model_Casts_Boolean.spec.ts
- packages/pinia-orm/tests/unit/model/Model_Casts_Number.spec.ts
- packages/pinia-orm/tests/unit/support/Utils_Compare_With_Operator.spec.ts
Adding "whereHas", "orHas", "orWhereHas", "doesntHave", "orDoesntHave", "whereDoesntHave" and "orWhereDoesntHave" to query
> feat(pinia-orm): add query methods

- docs/content/1.guide/4.repository/3.inserting-data.md
- docs/content/2.api/3.query/orderBy.md
- docs/content/2.api/3.query/with.md
- docs/content/2.api/3.query/withAll.md
- docs/content/2.api/3.query/withAllRecursive.md
- docs/content/2.api/4.repository/make.md
- packages/pinia-orm/src/repository/Repository.ts
- packages/pinia-orm/tests/unit/repository/Repository.spec.ts
Let's give `make` in repository the possibility to create multiple modles at once.
vuex-orm/vuex-orm-next#118
> feat(pinia-orm): add the possibility to create many models with "make" in repository

- docs/content/1.guide/2.model/1.getting-started.md
- docs/content/1.guide/2.model/4.decorators.md
- packages/pinia-orm/src/model/Model.ts
- packages/pinia-orm/src/model/attributes/Attribute.ts
- packages/pinia-orm/src/model/attributes/types/Boolean.ts
- packages/pinia-orm/src/model/attributes/types/Number.ts
- packages/pinia-orm/src/model/attributes/types/String.ts
- packages/pinia-orm/src/model/attributes/types/Type.ts
- packages/pinia-orm/src/model/decorators/Contracts.ts
- packages/pinia-orm/src/model/decorators/attributes/types/Bool.ts
- packages/pinia-orm/src/model/decorators/attributes/types/Num.ts
- packages/pinia-orm/src/model/decorators/attributes/types/Str.ts
- packages/pinia-orm/src/schema/Schema.ts
- packages/pinia-orm/tests/unit/model/Model_Attrs_Boolean.spec.ts
- packages/pinia-orm/tests/unit/model/Model_Attrs_Number.spec.ts
- packages/pinia-orm/tests/unit/model/Model_Attrs_String.spec.ts
- packages/pinia-orm/tests/unit/model/Model_Casts_Boolean.spec.ts
- packages/pinia-orm/tests/unit/model/Model_Casts_Number.spec.ts
- packages/pinia-orm/tests/unit/model/Model_Casts_String.spec.ts
- packages/pinia-orm/tests/unit/model/Model_Sanitize.spec.ts
vuex-orm/vuex-orm-next#95
It's a good idea to make fields per default null and throw a warning if they are set as `notNullable`
BREAKING CHANGES: Removed `nullable` and added `notNullable`. Fields are per default now null.
> feat(pinia-orm)!: Make fields default nullable

- docs/content/1.guide/1.getting-started/1.quick-start.md
- docs/content/1.guide/1.getting-started/3.typescript.md
- docs/content/1.guide/2.model/2.accessors.md
- docs/content/1.guide/2.model/3.casts.md
- docs/content/1.guide/2.model/4.decorators.md
- docs/content/1.guide/2.model/6.pinia-options.md
- docs/content/2.api/2.model/1.fields-attributes/attr.md
- docs/content/2.api/2.model/1.fields-attributes/boolean.md
- docs/content/2.api/2.model/1.fields-attributes/number.md
- docs/content/2.api/2.model/1.fields-attributes/string.md
- docs/content/2.api/2.model/1.fields-attributes/uid.md
- docs/content/2.api/2.model/2.fields-relations/belongs-to-many.md
- docs/content/2.api/2.model/2.fields-relations/belongs-to.md
- docs/content/2.api/2.model/2.fields-relations/has-many-by.md
- docs/content/2.api/2.model/2.fields-relations/has-many.md
- docs/content/2.api/2.model/2.fields-relations/has-one.md
- docs/content/2.api/2.model/2.fields-relations/morph-many.md
- docs/content/2.api/2.model/2.fields-relations/morph-one.md
- docs/content/2.api/2.model/2.fields-relations/morph-to.md
- docs/content/2.api/2.model/3.casts.md
- docs/content/2.api/2.model/3.mutators.md
- docs/theme.config.ts
- docs/yarn.lock
closes #148
To adept to new typescript standards `declare name: string` is now the recommonded way to define types in classes instead of `name!: string`
> docs: move to `declare` as typescript standard and add a new page

- packages/pinia-orm/src/query/Query.ts
- packages/pinia-orm/tests/feature/repository/retrieves_has.spec.ts
Fixes: #292 
Add a check for has queries if the relations is a single or many relation
> fix(pinia-orm): `(where)has` queries are not working with 1:1 relations

- packages/pinia-orm/src/model/Model.ts
- packages/pinia-orm/src/model/attributes/relations/BelongsToMany.ts
- packages/pinia-orm/tests/feature/relations/belongs_to_many_save.spec.ts
#363
Currently it wasn't possible to have multiple mn pivot tables with the same models. Kind of edge case 🤔  
Look into related issue for more detail.
> fix(pinia-orm): multiple belongsTo relationships between 2 entities lead to unintended outcome

- docs/content/1.guide/2.model/1.getting-started.md
- docs/content/2.api/2.model/1.fields-attributes/attr.md
- docs/content/2.api/2.model/1.fields-attributes/boolean.md
- docs/content/2.api/2.model/1.fields-attributes/number.md
- docs/content/2.api/2.model/1.fields-attributes/string.md
- packages/pinia-orm/src/model/Model.ts
- packages/pinia-orm/src/model/attributes/types/Boolean.ts
- packages/pinia-orm/src/model/attributes/types/Number.ts
- packages/pinia-orm/src/model/attributes/types/String.ts
- packages/pinia-orm/src/model/attributes/types/Type.ts
- packages/pinia-orm/src/model/decorators/attributes/types/Attr.ts
- packages/pinia-orm/src/model/decorators/attributes/types/Bool.ts
- packages/pinia-orm/src/model/decorators/attributes/types/Num.ts
- packages/pinia-orm/src/model/decorators/attributes/types/Str.ts
- packages/pinia-orm/tests/unit/model/Model_Attrs_String.spec.ts
closes #542 
Add the possibilty to pass closures for attributes as default value.
> feat(pinia-orm): Attributes can now accept closures for default value

- docs/content/1.guide/2.model/7.single-table-inheritance.md
- packages/pinia-orm/src/model/Model.ts
- packages/pinia-orm/src/model/attributes/types/Type.ts
- packages/pinia-orm/src/query/Query.ts
- packages/pinia-orm/tests/unit/model/Model_STI.spec.ts
closes #522, related #519
If you used a childRepo saving it without type than its defined default is not used:
e.g.:
````ts
class Animal extends Model {
static entity = 'animals'
static fields() {
return {
id: this.attr(null),
type: this.attr('animal'),
}
}
static types() {
return {
animal: Animal,
dog: Dog,
}
}
}
class Dog extends Animal {
static entity = 'dogs'
static baseEntity = 'animals'
static fields() {
return {
...super.fields(),
type: this.attr('dog'),
race: this.attr('terrier'),
}
}
}
const animalsRepo = useRepo(Animal)
animalsRepo.save([
{
id: 1,
type: 'animal',
},
{
id: 2,
type: 'dog',
race: 'Rattler',
},
{
id: 3,
type: 'cat',
race: 'red',
},
])
useRepo(Dog).save({
id: 4,
race: 'Rattler',
})
````
---
Also updated docs with an example for decorators.
---
Removed unnecessary …
> fix(pinia-orm): using childRepo (STI) for saving without type defined

- packages/pinia-orm/src/query/Query.ts
- packages/pinia-orm/tests/feature/repository/delete_with_relations.spec.ts
The `onDelete('cascade')` method is not working wtih n:m relations (BelongsToMany).
> fix(pinia-orm): delete on cascade doesn't work with n:m relations

- docs/content/2.api/1.composables/2.helpers/use-collect.md
- docs/content/2.api/1.composables/2.helpers/use-sort-by.md
- packages/pinia-orm/src/composables/collection/useCollect.ts
- packages/pinia-orm/src/composables/collection/useSortBy.ts
- packages/pinia-orm/src/support/Utils.ts
- packages/pinia-orm/tests/unit/composables/Use_Collect.spec.ts
#634 
Adding the option to sort collections case insensitive:
````ts
const userCollection = useCollect(useRepo(User).make([
{ id: 1, name: 'James', age: 40, post: { id: 1, title: 'Title1' } },
{ id: 2, name: 'john', age: 30, post: { id: 2, title: 'Title2' } },
{ id: 3, name: 'David', age: 20 },
])).sortBy('name', 'SORT_FLAG_CASE')
````
> feat(pinia-orm): Add the option to sort case insensitive with `sortBy`

- packages/pinia-orm/src/model/Model.ts
- packages/pinia-orm/tests/feature/repository/delete_with_relations.spec.ts
closes #748
If you have the name attributes with diffrent behaviour and using `onDelete` it causes an error because the attribute names are registered on model level instead for the entity itself.
> fix(pinia-orm): @OnDelete on same model attrs leads to undefined error

- packages/pinia-orm/src/query/Query.ts
related #774 
Since `all()` ignores the query builder it shouldn't be able to be called from the query builder. This helps to have more exspected results so that `useRepo(User).all()` is correct but `useRepo(User).query().all()` not.
> refactor!: make `all()` not accessible from query

- docs/content/2.api/4.repository/new.md
- packages/pinia-orm/src/query/Query.ts
- packages/pinia-orm/src/repository/Repository.ts
- packages/pinia-orm/tests/feature/hooks/created.spec.ts
- packages/pinia-orm/tests/feature/hooks/creating.spec.ts
- packages/pinia-orm/tests/feature/hooks/saved.spec.ts
- packages/pinia-orm/tests/feature/hooks/saving.spec.ts
> fix(pinia-orm): `new` doesnt fire creating or created hook

- packages/pinia-orm/src/model/attributes/relations/BelongsToMany.ts
- packages/pinia-orm/tests/performance/save_belongs_to_many_relation.spec.ts
closes #823
Reduced the number of queries for `belongsToMany` improving speed by over 70%-80%
> perf(pinia-orm): Querying models with belongsToMany are slow

- docs/content/1.guide/3.relationships/1.getting-started.md
- docs/content/2.api/2.model/1.options/2.fields-relations/belongs-to.md
- docs/content/2.api/2.model/1.options/2.fields-relations/has-many.md
- docs/content/2.api/2.model/1.options/2.fields-relations/has-one.md
- packages/pinia-orm/src/model/Model.ts
- packages/pinia-orm/src/model/attributes/relations/BelongsTo.ts
- packages/pinia-orm/src/model/attributes/relations/HasMany.ts
- packages/pinia-orm/src/model/attributes/relations/HasOne.ts
- packages/pinia-orm/src/model/attributes/relations/Relation.ts
- packages/pinia-orm/src/model/decorators/attributes/relations/BelongsTo.ts
- packages/pinia-orm/src/model/decorators/attributes/relations/HasMany.ts
- packages/pinia-orm/src/model/decorators/attributes/relations/HasOne.ts
- packages/pinia-orm/src/query/Query.ts
- packages/pinia-orm/tests/feature/relations/belongs_to_retrieve_composite.spec.ts
- packages/pinia-orm/tests/feature/relations/has_many_retrieve_composite.spec.ts
- packages/pinia-orm/tests/feature/relations/has_many_save_custom_key.spec.ts
- packages/pinia-orm/tests/feature/relations/has_one_retrieve_composite.spec.ts
closes #829
Adding support of composite keys for `belongsTo`, `hasOne` and `hasMany`. So you can do something like this:
````ts
class Phone extends Model {
static entity = 'phones'
@Attr() declare id: number
@Attr() declare userId: number
@Attr() declare userSecondId: number
@Str('') declare number: string
}
class User extends Model {
static entity = 'users'
static primaryKey = ['id', 'secondId']
@Attr() declare id: number
@Attr() declare secondId: number
@Str('') declare name: string
@HasOne(() => Phone, ['userId', 'userSecondId'])
phone!: Phone | null
}
````
> feat(pinia-orm): Support of composite key for some relations

- packages/pinia-orm/src/query/Query.ts
- packages/pinia-orm/src/repository/Repository.ts
- packages/pinia-orm/tests/unit/PiniaORM.spec.ts
closes #853
The hydration cache is almost now the same as the query cache. The hydration caching now doesn't use a deep compare anymore so that the speed will improve significatly for large model opjects. The perfomance should be 20%-80% better.
> perf(pinia-orm): Improve caching for hydrated models

- packages/pinia-orm/src/cache/SharedHydratedDatakCache.ts
- packages/pinia-orm/src/composables/useDataStore.ts
- packages/pinia-orm/src/composables/useRepo.ts
- packages/pinia-orm/src/composables/useStoreActions.ts
- packages/pinia-orm/src/query/Query.ts
- packages/pinia-orm/src/repository/Repository.ts
- packages/pinia-orm/tests/unit/composables/Use_Collect.spec.ts
- packages/pinia-orm/tests/unit/model/Model_Relations.spec.ts
- packages/pinia-orm/tests/unit/repository/Repository.spec.ts
closes #1058
1. This is adding a shared hydration cache to improve performance accross repositories. 
2. The pinia actions if called directly now also trigger the store actions so hooks & hydration cache is updated
> feat(pinia-orm): Shared hydration cache & pinia actions triggering repo actions

- packages/pinia-orm/src/model/Model.ts
The new check ensures that the value is an instance of `Date` in the `serializeValue function` of `Model.ts`.
Adding a condition like `if ('toISOString' in value')` to check for the existence of a method on an object can lead to issues `in` JavaScript because it does not accurately check whether the method actually exists and can be called. This is because objects in JavaScript can have inherited properties, and the `in` operator also checks for properties in the object's prototype chain. As a result, using the `in` operator to check for the existence of a method on an object can sometimes result in unexpected behaviour.
In my personal experience, I had a big headache with the `in` operator in `Python`, and since then, I have never used `in` in any language with similar behaviour. Because …
> fix(pinia-orm): Improve Date serialization in Model class

- docs/content/1.guide/3.relationships/2.one-to-one.md
The `Phone` model was using `users` as the entity name. The same being used for the `User` model.
The `Phone` model was using `users` as the entity name. The same being used for the `User` model.
> docs: Fixed typo on entity name in example

- packages/pinia-orm/package.json
- packages/pinia-orm/src/composables/collection/useGroupBy.ts
- packages/pinia-orm/src/composables/collection/useSortBy.ts
- packages/pinia-orm/src/model/Model.ts
- packages/pinia-orm/src/model/attributes/relations/BelongsToMany.ts
- packages/pinia-orm/src/model/attributes/relations/MorphToMany.ts
- packages/pinia-orm/src/query/Query.ts
- packages/pinia-orm/src/support/Utils.ts
- packages/pinia-orm/tsconfig.json
- pnpm-lock.yaml
MInor updates are not working cause of typscript update
>  chore(pinia-orm): Remove deprecated tsconfig `suppressImplicitAnyIndexErrors`

- packages/pinia-orm/src/model/Model.ts
- packages/pinia-orm/src/store/Config.ts
- packages/pinia-orm/tests/unit/model/Model.spec.ts
closes #1569 
The orginal data state was always overwritten by the last model called. That way `$getOrginal` never worked correctly.
> fix(pinia-orm-1569): Wrong behaviour of `$getOriginal`

- docs/content/1.guide/3.relationships/1.getting-started.md
Removed a duplicate section showing how to retrieve nested relationships
Removed this duplicated section:
> docs: removed duplicate "Relationsihps > Getting Started > Loading Nested Realtionship" section

- docs/content/1.guide/1.getting-started/4.typescript.md
- docs/content/1.guide/4.repository/1.getting-started.md
- docs/content/2.api/3.query/load.md
Fix typo "form" vs "from" in getting_started/typescript documtation
> docs: Couple of typos

- docs/content/1.guide/2.model/7.single-table-inheritance.md
> docs(pinia-orm): Broken link or missing reference

- docs/content/1.guide/3.relationships/3.one-to-many.md
- docs/content/1.guide/4.repository/2.retrieving-data.md
- docs/content/1.guide/4.repository/5.deleting-data.md
https://github.com/CodeDredd/pinia-orm/pull/1206
Now that we can query records with composite primary in 1.7 it should probably be in the docs. This pr adds it to the retrieving and deleting models section.
> docs: add Compositekey lookup

- docs/content/1.guide/2.model/7.single-table-inheritance.md
The .insert had the `{data:...}` field from vuex-orm in the examples. This pr removes that.
The .insert had the `{data:...}` field from vuex-orm in the examples. This pr removes the data field.
> docs: Fixed insert incorrect example in single table inheritance docs

- packages/pinia-orm/src/schema/Schema.ts
- packages/pinia-orm/tests/feature/relations/morph_many_save.spec.ts
> fix(pinia-orm): `Uncaught TypeError: parent.$fields()[key] is undefied` when inserting nested data with polymorphic relationships

- docs/app.config.ts
- docs/components/content/BackgroundLogo.vue
- docs/components/content/app/AgoliaDocSearch.client.vue
- docs/components/content/app/AppHeader.vue
- docs/components/content/landing/CardGrid.vue
- docs/components/content/layout/BasicLayout.vue
- docs/content/1.guide/1.getting-started/1.quick-start.md
- docs/content/1.index.md
- docs/nuxt.config.ts
- docs/package.json
- docs/server/api/search.ts
- docs/tailwind.config.ts
- docs/yarn.lock
> docs: Update depencies & fix small display errors

- packages/pinia-orm/src/schema/Schema.ts
- packages/pinia-orm/tests/feature/relations/belongs_to_save.spec.ts
- packages/pinia-orm/tests/feature/relations/has_one_save.spec.ts
- packages/pinia-orm/tests/feature/relations/morph_one_save.spec.ts
- packages/pinia-orm/tests/feature/relations/morph_to_save.spec.ts
- packages/pinia-orm/tests/performance/prevent_rerender_of_child_components.spec.ts
- packages/pinia-orm/tests/performance/save_belongs_to_many_relation.spec.ts
- packages/pinia-orm/tests/performance/save_has_many_relation.spec.ts
- packages/pinia-orm/tests/performance/speed_find.spec.ts
> feat(pinia-orm): Throw an error when trying to save a list into a 1:1 relationship

- .github/ISSUE_TEMPLATE/bug_report.yml
- .github/ISSUE_TEMPLATE/feature_request.yml
https://github.com/CodeDredd/pinia-orm/discussions/1619
Jut making the issue template a bit more user friendly.
> chore: Issue template improvement

- packages/pinia-orm/src/model/Model.ts
- packages/pinia-orm/src/query/Query.ts
- packages/pinia-orm/tests/feature/repository/delete_with_relations.spec.ts
resolves #1620
Adding support for composite key `destroy` because lookup already works with it. Also adapted `onDelete` to work with it.
> feat(pinia-orm): Composite primary key can now be used with `destroy` and `onDelete`

- packages/pinia-orm/src/model/attributes/relations/HasMany.ts
https://github.com/CodeDredd/pinia-orm/issues/1799
This fix resolves the issue of nested relationships loading incorrectly when the identifiers of both entities are complex.
e.g. 
``` typescript
class LeadPointProduct extends Model {
static entity = 'leads/point/products';
static primaryKey = ['leadId', 'pointId', 'productId'];
static fields() {
return {
leadId: this.attr(null),
pointId: this.attr(null),
productId: this.attr(null),
};
}
declare leadId: number;
declare pointId: number;
declare productId: number;
}
class LeadPoint extends Model {
static entity = 'leads/points';
static primaryKey = ['leadId', 'pointId'];
static fields() {
return {
leadId: this.attr(null),
pointId: this.attr(null),
// relations
leadPointProducts: this.hasMany(
LeadPointProduct,
['leadId', 'pointId'], …
```
> Fix eager load relations with complex foreign/local keys

- packages/nuxt/src/runtime/plugin.vue3.ts
This is a DX improvement when developing - we can avoid loading the entire barrel file at `#app` by using the new granular imports merged in https://github.com/nuxt/nuxt/pull/23951.
> fix: import nuxt composables from #imports

- docs-playground/yarn.lock
- packages/pinia-orm/src/composables/useRepo.ts
> fix(pinia-orm): Typings of `useRepo` with Repository are broken

- packages/pinia-orm/src/model/attributes/relations/BelongsToMany.ts
- packages/pinia-orm/src/model/attributes/relations/MorphToMany.ts
- packages/pinia-orm/tests/unit/model/Model_Mutators.spec.ts
> fix(pinia-orm): Mutators/Casts on related models with belongsToMany were wrong

- packages/pinia-orm/src/types/repository.ts
> fix(pinia-orm): `.find` returning type `any` when using `useRepo`

- docs/content/3.plugins/1.introduction.md
- docs/content/3.plugins/2.axios/1.guide/1.setup.md
- docs/content/3.plugins/2.axios/1.guide/2.configuration.md
- packages/axios/test/setup.ts
- packages/pinia-orm/src/store/Store.ts
- packages/pinia-orm/tests/helpers.ts
- playgrounds/nuxt3/orm.ts
- playgrounds/nuxt3/package.json
- pnpm-lock.yaml
resolves #1901, resolves #1859, resolves #1694, resolves #1687
This is a breaking change which is necessary to keep aligned with pinia plugin types.
Instead of using `createORM().use(plugin)` you must use `createORM({ plugins: [plugin] })`
BREAKING-CHANGE: Removed `createORM().use(PUGIN)`. Use `createORM({plugins: [PLUGIN] })` instead.
> fix(pinia-orm): Change plugin registration to be still compatible with pinia types

- packages/pinia-orm/src/model/Model.ts
- packages/pinia-orm/tests/unit/model/Model_Isolation.spec.ts
resolves #1953
The `original` static property in the Model class stores original states using only the model's ID as the key, causing different model types to overwrite each other's original states when they share the same ID.
This PR is separating/namespacing the original states by model entity
> fix(pinia-orm): Model original data is overwritten by different namspace models with same ID

- packages/pinia-orm/src/support/Utils.ts
- packages/pinia-orm/tests/unit/model/Model_Attrs_UID.spec.ts
> fix(pinia-orm): UID Decorator: Setting Custom Alphabet Results in "undefined" Instead of Characters in UIDs

- packages/pinia-orm/src/support/Utils.ts
resolves #1858 
This is a maybe fix....still needs a unit test to find the reason for breaking....
> fix(pinia-orm): Ordering sometimes wrong with Query.orderBy and UseCollect.sortBy

- packages/axios/package.json
- packages/normalizr/package.json
- packages/nuxt/package.json
- packages/pinia-orm/package.json
[compare changes](https://github.com/CodeDredd/pinia-orm/compare/v1.10.1...v2.0.0)
- **pinia-orm:** ⚠️  Moving to Pinia v3 ([#1981](https://github.com/CodeDredd/pinia-orm/pull/1981))
- **nuxt:** Make sure to use correct pinia/nuxt version ([#1986](https://github.com/CodeDredd/pinia-orm/pull/1986))
- **pinia-orm:** Remove nanoid async in test setup ([0485786](https://github.com/CodeDredd/pinia-orm/commit/0485786))
- Update vitest ([4bc658f](https://github.com/CodeDredd/pinia-orm/commit/4bc658f))
- Update changelog gen script ([791eaa3](https://github.com/CodeDredd/pinia-orm/commit/791eaa3))
- Fix changelog script ([4863481](https://github.com/CodeDredd/pinia-orm/commit/4863481))
- Fix changelog script ([8e1d2d4](https://github.com/CodeDredd/pinia-orm/commit/8e1d2d4))
- Add correct author …
> v2.0.0-alpha.1

- packages/pinia-orm/src/model/attributes/relations/HasManyThrough.ts
- packages/pinia-orm/tests/feature/relations/has_many_through_retrieve.spec.ts
> fix(pinia-orm): `hasManyThrough` doesn't work correctly with mulitple model instances
