CodeDredd/pinia-orm

- docs/content/en/usage.md
> wrong link in usage.md

- packages/pinia-orm/src/model/attributes/relations/BelongsToMany.ts
- packages/pinia-orm/tests/feature/relations/belongs_to_many_save_custom_key.spec.ts
> fix(pinia-orm): belongsToMany was behaving incorrectly nested

- docs/content/1.index.md
found on docs file 1.index.md:15
> fix: typo - misspelled pinia for pina

- packages/pinia-orm/src/query/Query.ts
> fix(pinia-orm): A few Query methods have wrong return type

- docs/content/1.guide/5.nuxt/1.setup.md
- playgrounds/nuxt2comp/nuxt.config.js
- playgrounds/nuxt2comp/package.json
- playgrounds/nuxt2comp/yarn.lock
> fix(pinia-orm): Can't get it working on Nuxt2

- docs/content/1.guide/2.model/5.lifecycle-hooks.md
- docs/content/2.api/2.model/4.hooks/retrieved.md
- packages/pinia-orm/src/model/Model.ts
- packages/pinia-orm/src/model/attributes/relations/BelongsTo.ts
- packages/pinia-orm/src/model/attributes/relations/BelongsToMany.ts
- packages/pinia-orm/src/model/attributes/relations/HasMany.ts
- packages/pinia-orm/src/model/attributes/relations/HasManyBy.ts
- packages/pinia-orm/src/model/attributes/relations/HasOne.ts
- packages/pinia-orm/src/model/attributes/relations/MorphMany.ts
- packages/pinia-orm/src/model/attributes/relations/MorphOne.ts
- packages/pinia-orm/src/model/attributes/relations/MorphTo.ts
- packages/pinia-orm/src/query/Query.ts
- packages/pinia-orm/tests/feature/hooks/retrieved.spec.ts
> feat(pinia-orm): add `retrieved` life cycle hook

- packages/nuxt/package.json
- packages/nuxt/src/runtime/plugin.ts
- playgrounds/nuxt2comp/package.json
- playgrounds/nuxt2comp/tsconfig.json
- playgrounds/nuxt2comp/yarn.lock
- playgrounds/nuxt3/nuxt.config.ts
- playgrounds/nuxt3/package.json
- playgrounds/nuxt3/yarn.lock
Since version 0.3 of `@pina/nuxt` some changes were introduced that are breaking the plugin
See chngelog for details -> https://github.com/vuejs/pinia/blob/v2/packages/nuxt/CHANGELOG.md
> fix(nuxt): adept changes from `@pinia/nuxt`

- packages/normalizr/.eslintignore
- packages/normalizr/.eslintrc
- packages/normalizr/.gitignore
- packages/normalizr/LICENSE
- packages/normalizr/README.md
- packages/normalizr/build.config.ts
- packages/normalizr/index.d.ts
- packages/normalizr/package.json
- packages/normalizr/src/index.js
- packages/normalizr/src/schemas/Array.js
- packages/normalizr/src/schemas/Entity.js
- packages/normalizr/src/schemas/ImmutableUtils.js
- packages/normalizr/src/schemas/Object.js
- packages/normalizr/src/schemas/Polymorphic.js
- packages/normalizr/src/schemas/Union.js
- pnpm-lock.yaml
The `normalizr` package is making 22% of the size. TIme to change it and make a own package where only the functions are which are used!
> build(normalizr): create own `normalizr` package

- docs/content/1.guide/2.model/1.getting-started.md
https://github.com/CodeDredd/pinia-orm/discussions/210#discussioncomment-3453787
Wrong examples for uid libs.
> docs: wrong uid example

- packages/pinia-orm/src/support/Utils.ts
- packages/pinia-orm/tests/feature/relations/belongs_to_many_retrieve.spec.ts
- packages/pinia-orm/tests/feature/relations/belongs_to_many_save.spec.ts
- packages/pinia-orm/tests/unit/model/Model_Relations.spec.ts
- packages/pinia-orm/tests/unit/support/Utils_Generate_Id.spec.ts
> test(pinia-orm): Add missing tests for better coverage

- packages/pinia-orm/src/query/Query.ts
- packages/pinia-orm/src/support/Utils.ts
- packages/pinia-orm/tests/performance/save_has_many_relation.spec.ts
closes #354 
Add fallback if `Buffer` is not defined and fix cach config inheritance.
> fix(pinia-orm): fallback for "Buffer is not defined" & fix cache config

- packages/pinia-orm/src/model/Model.ts
- packages/pinia-orm/src/model/attributes/relations/BelongsToMany.ts
- packages/pinia-orm/tests/feature/relations/belongs_to_many_save.spec.ts
closes #363 
Last fixed didnt resolve the issue correctly. The tests were also wrong.
> fix(pinia-orm): multiple belongsToMany relations still wrong saved

- docs/content/1.guide/4.repository/2.retrieving-data.md
N/A
- [ x] 📖 Documentation (updates to the documentation or readme)
> docs: orderBy was used in documentation for chaining groupBy

- docs/package.json
- docs/yarn.lock
- renovate.json
closes #541 
nuxt 3 RC 13 breaks the doc build
> fix(docs): docs broken with nuxt3.0.0-rc.13

- docs/content/1.guide/1.getting-started/1.quick-start.md
- docs/content/1.guide/2.model/1.getting-started.md
- docs/content/1.guide/2.model/2.accessors.md
- docs/content/1.guide/2.model/3.casts.md
- docs/content/1.guide/2.model/5.lifecycle-hooks.md
- docs/content/1.guide/2.model/6.pinia-options.md
- docs/content/1.guide/3.relationships/1.getting-started.md
- docs/content/1.guide/4.repository/2.retrieving-data.md
- docs/content/1.guide/4.repository/3.inserting-data.md
I spotted some minor mistakes in the docs (typos, formatting, etc.) and did the PR with the changes. @CodeDredd feel free to further tweak if you like to do so. There would be some other change to do (ie Typescript is spelled as TypeScript), let me know if you are interested.
Finally, for some reason I can't build the docs (nuxt theme dependency error IIRC) so I didn't test what I did.
> docs: fix typos + minor tweaks

- docs/content/3.changelog.md
- docs/nuxt.config.ts
- docs/package.json
- docs/yarn.lock
Release site is still crashing the site.
> fix(docs): release site not working

- docs/content/1.guide/1.getting-started/2.usage.md
Fix typo `pina` to `pinia` and `defineSotre` to `defineStore`
> docs: typo in usage

- docs/content/1.guide/5.nuxt/1.setup.md
closes #628 
Add info about requirements for nuxt 2 users
> docs(pinia-orm): Add requirements info for nuxt 2 users

- docs/content/1.guide/1.getting-started/1.quick-start.md
> docs: typo in example of quick-start.md

- packages/pinia-orm/src/query/Query.ts
related #659 
Improve hydration check
> perf(pinia-orm): Improve hydrating check

- docs/app.config.ts
- docs/components/Logo.vue
- docs/components/content/ChangeLog.vue
- docs/content/1.index.md
- docs/content/3.changelog.md
- docs/nuxt.config.ts
- docs/package.json
- docs/tailwind.config.ts
- docs/tokens.config.ts
- docs/yarn.lock
> chore: update docus to the latest nuxt version

- docs/content/1.guide/1.getting-started/3.typescript.md
Fixed typo on word "recommended"
> docs: corrected spelling of 'recommended'

- docs/content/1.guide/2.model/1.getting-started.md
- docs/content/1.guide/2.model/2.accessors.md
- docs/content/1.guide/4.repository/2.retrieving-data.md
The `:::tip` component does not exist in and was not showing correctly on the rendered output
Changed the `:::tip` component for an `::alert{type="info"}` component instead
> docs: Changed :::tip for ::alert{type='info'}

- packages/pinia-orm/src/model/Model.ts
- packages/pinia-orm/tests/feature/hooks/created.spec.ts
closes #1067
Fix using class types in hooks.
> fix(pinia-orm): Types in hooks were conflicting

- docs/content/1.guide/4.repository/5.deleting-data.md
> docs(pinia-orm): remove not correct await

- docs/content/2.api/4.repository/make.md
- docs/content/2.api/4.repository/new.md
- packages/pinia-orm/src/query/Query.ts
- packages/pinia-orm/src/repository/Repository.ts
- packages/pinia-orm/tests/feature/hooks/creating.spec.ts
> feat(pinia-orm): Add the option for new not to persist the model

- packages/pinia-orm/src/model/Model.ts
- packages/pinia-orm/tests/unit/model/Model.spec.ts
> fix(pinia-orm): `$refresh()` is not working

- packages/nuxt/build.config.ts
- packages/nuxt/package.json
- playgrounds/nuxt3/package.json
- playgrounds/nuxt3/yarn.lock
- pnpm-lock.yaml
> fix(nuxt): Nuxt 3 throws error on build & dev

- docs/content/1.guide/1.getting-started/4.typescript.md
> docs(pinia-orm-1382): Typo in docs examples: form -> from

- docs/content/3.plugins/2.axios/1.guide/1.setup.md
this pr fix a typo on axios plugin setup guide
> fix(docs): fix typo on axios setup guide

- packages/pinia-orm/package.json
- packages/pinia-orm/tsconfig.json
- pnpm-lock.yaml
Moving in tsconfig from moduleResolution `node` to `bundler`.
> chore(pinia-orm): Move to moduleResolution `bundler`

- packages/pinia-orm/src/model/attributes/relations/BelongsToMany.ts
- packages/pinia-orm/src/model/attributes/relations/MorphToMany.ts
- packages/pinia-orm/tests/feature/repository/retrieves_order_by.spec.ts
> fix(pinia-orm): `pivot` helper fields are not deleted or removed.

- docs/content/1.guide/3.relationships/5.polymorphic.md
> docs(pinia-orm): MorphToMany example Taggable is missing primaryKey

- packages/pinia-orm/package.json
- pnpm-lock.yaml
> fix(pinia-orm): Failed to resolve import "vue-demi"

- packages/nuxt/package.json
> refactor(nuxt): Make sure to use correct pinia/nuxt version

- packages/axios/package.json
- packages/normalizr/package.json
- packages/nuxt/package.json
- packages/pinia-orm/package.json
> 2.0.0-alpha.2 is the next release.
>
> **Timetable**: to be announced.
[compare changes](https://github.com/CodeDredd/pinia-orm/compare/v2.0.0-alpha.1...v2.0.0)
- **pinia-orm:** Peerdependencies are causing issues resolves #2000 ([#2000](https://github.com/CodeDredd/pinia-orm/issues/2000))
- **axios:** Peerdependencies are causing issues resolves #1997 ([#1997](https://github.com/CodeDredd/pinia-orm/issues/1997))
- **nuxt:** Wrong static import causing installation problems ([0a6c91f](https://github.com/CodeDredd/pinia-orm/commit/0a6c91f))
- **pinia-orm:** Boolean Type not casting truthy values ([#1994](https://github.com/CodeDredd/pinia-orm/pull/1994))
- Use v2 tags for changelog gen ([cb0f4c0](https://github.com/CodeDredd/pinia-orm/commit/cb0f4c0))
- Remove lerna …
> v2.0.0-alpha.2
